# Generated by Django 6.0.4 on 2026-04-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test',
            options={},
        ),
    ]
