# Generated by Django 6.0.4 on 2026-04-20 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='game',
        ),
        migrations.AddField(
            model_name='car',
            name='game',
            field=models.ManyToManyField(to='api.game'),
        ),
    ]
