# Generated by Django 6.0.4 on 2026-04-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_car_game_car_game'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='game',
            new_name='games',
        ),
    ]
