# Generated by Django 6.0.4 on 2026-04-20 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_game_car_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='setup',
            old_name='downloads',
            new_name='downloads_count',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='ratingCount',
            new_name='rating_count',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='setupData',
            new_name='setup_data',
        ),
        migrations.RenameField(
            model_name='setup',
            old_name='videoUrl',
            new_name='video_url',
        ),
    ]
