# Generated by Django 6.0.4 on 2026-04-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_downloads_setup_downloads_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
